# Generated by Django 5.2 on 2025-05-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticketmaster_id", models.CharField(max_length=100, unique=True)),
                ("artist", models.CharField(max_length=255)),
                ("venue", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("price_range", models.CharField(blank=True, max_length=100)),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("image_url", models.URLField(blank=True)),
                ("event_url", models.URLField()),
                ("popularity_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="concerts_co_date_be5ed1_idx"),
                    models.Index(
                        fields=["popularity_score"],
                        name="concerts_co_popular_fdef0c_idx",
                    ),
                    models.Index(
                        fields=["artist"], name="concerts_co_artist_c4826c_idx"
                    ),
                ],
            },
        ),
    ]
