# Generated by Django 5.2 on 2025-05-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0001_initial_concert_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="concert",
            old_name="genre",
            new_name="genres",
        ),
    ]
