# Generated by Django 5.2 on 2025-05-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0002_rename_genre_concert_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="event_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="concert",
            index=models.Index(
                fields=["event_name"], name="concerts_co_event_n_9f9082_idx"
            ),
        ),
    ]
