# Generated by Django 5.1.2 on 2024-10-17 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "spotify_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=2, null=True)),
                ("explicit_content", models.BooleanField(default=False)),
                ("external_url", models.URLField(blank=True, null=True)),
                ("followers_count", models.IntegerField(default=0)),
                ("href", models.URLField(blank=True, null=True)),
                ("product", models.CharField(blank=True, max_length=50, null=True)),
                ("uri", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserTopArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_range",
                    models.CharField(
                        choices=[
                            ("long_term", "Long Term"),
                            ("medium_term", "Medium Term"),
                            ("short_term", "Short Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rank", models.IntegerField()),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.artist"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserTopTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_range",
                    models.CharField(
                        choices=[
                            ("long_term", "Long Term"),
                            ("medium_term", "Medium Term"),
                            ("short_term", "Short Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rank", models.IntegerField()),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.track"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
