# Generated by Django 5.1.2 on 2024-10-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
        ("users", "0002_user_access_token_user_refresh_token_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usertopartist",
            unique_together={("user", "artist", "time_range")},
        ),
    ]
