# Generated by Django 5.1.2 on 2024-10-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_alter_album_release_date"),
        ("users", "0003_alter_usertopartist_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usertoptrack",
            unique_together={("user", "track", "time_range")},
        ),
    ]
