# Generated by Django 5.1.3 on 2024-12-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0004_alter_album_release_date"),
        ("users", "0004_alter_usertoptrack_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSavedAlbums",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "spotify_url",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("popularity", models.IntegerField()),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.album"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "album")},
            },
        ),
    ]
