# Generated by Django 5.1.3 on 2024-12-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0008_rename_genre_id_genre_id_remove_genre_genre_name_and_more"),
        ("users", "0005_usersavedalbums"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGenreListening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listen_count", models.IntegerField(default=0)),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_listenings",
                        to="music.genre",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genre_listenings",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "genre")},
            },
        ),
    ]
