# Generated by Django 5.1.3 on 2024-12-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_usergenrelistening"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersavedalbums",
            name="art",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
