# Generated by Django 5.1.3 on 2025-01-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_usersavedalbums_art"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
