# Generated by Django 5.1.3 on 2025-01-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_access_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
