# Generated by Django 5.1.3 on 2025-01-21 04:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_refresh_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertopartist",
            name="time_collected",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="usertoptrack",
            name="time_collected",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
