# Generated by Django 5.1.3 on 2025-01-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_usertopartist_time_collected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertoptrack",
            name="recently_listened",
            field=models.BooleanField(default=False),
        ),
    ]
