# Generated by Django 5.1.3 on 2025-01-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_usertoptrack_recently_listened"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertoptrack",
            name="played_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
