# Generated by Django 5.1.5 on 2025-02-11 03:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0016_playlist_tracks"),
        ("users", "0012_usertoptrack_played_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoundscapeUser",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="users.soundscapeuser",
            ),
        ),
    ]
