# Generated by Django 5.1.5 on 2025-02-14 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0016_playlist_tracks"),
        ("users", "0013_soundscapeuser_reviews_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="users.soundscapeuser",
            ),
        ),
    ]
