# Generated by Django 5.1.5 on 2025-02-14 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0016_playlist_tracks"),
        ("users", "0014_alter_user_user_id_reviews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
        migrations.AddField(
            model_name="soundscapeuser",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soundscape_user",
                to="users.user",
            ),
        ),
    ]
