# Generated by Django 5.1.5 on 2025-02-17 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0016_playlist_tracks"),
        ("users", "0015_remove_user_user_id_soundscapeuser_profile_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="soundscapeuser",
            name="google_user_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="soundscapeuser",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
