# Generated by Django 5.1.3 on 2025-02-18 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0016_playlist_tracks"),
        ("users", "0016_soundscapeuser_google_user_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "un_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("text", models.CharField(blank=True, max_length=1000, null=True)),
                ("rating", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.track"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
