# Generated by Django 5.1.3 on 2025-02-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_reviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="Minion",
            fields=[
                (
                    "un_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
