# Generated by Django 5.1.3 on 2025-02-18 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_minion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Minion",
        ),
    ]
