# Generated by Django 5.1.3 on 2025-02-18 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_delete_minion"),
    ]

    operations = [
        migrations.AddField(
            model_name="soundscapeuser",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
