# Generated by Django 5.1.3 on 2025-02-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_soundscapeuser_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soundscapeuser",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
