# Generated by Django 5.1.3 on 2025-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_soundscapeuser_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="soundscapeuser",
            name="pfp",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
