# Generated by Django 5.1.5 on 2025-03-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_soundscapeuser_pfp"),
    ]

    operations = [
        migrations.AddField(
            model_name="soundscapeuser",
            name="forgotPasswordTokenExpiry",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="soundscapeuser",
            name="verifyTokenExpiry",
            field=models.DateTimeField(null=True),
        ),
    ]
