# Generated by Django 5.1.5 on 2025-03-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_soundscapeuser_forgotpasswordtokenexpiry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="soundscapeuser",
            name="forgotPasswordToken",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="soundscapeuser",
            name="verifyToken",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
