# Generated by Django 5.1.5 on 2025-03-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_soundscapeuser_forgotpasswordtoken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="soundscapeuser",
            name="isVerified",
            field=models.BooleanField(default=False),
        ),
    ]
