# Generated by Django 5.1.5 on 2025-03-25 03:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_soundscapeuser_isverified"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergenrelistening",
            name="time_collected",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
