# Generated by Django 5.1.5 on 2025-03-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_usergenrelistening_time_collected"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergenrelistening",
            name="time_range",
            field=models.CharField(
                choices=[
                    ("short_term", "Short Term"),
                    ("medium_term", "Medium Term"),
                    ("long_term", "Long Term"),
                ],
                default="short_term",
                max_length=50,
            ),
        ),
    ]
