# Generated by Django 5.1.5 on 2025-03-25 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0016_playlist_tracks"),
        ("users", "0027_usergenrelistening_time_range"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usergenrelistening",
            unique_together={("user", "genre", "time_range")},
        ),
    ]
