# Generated by Django 5.1.5 on 2025-03-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_usergenrelistening_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usergenrelistening",
            unique_together=set(),
        ),
    ]
