# Generated by Django 5.1.3 on 2025-03-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_alter_usergenrelistening_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="soundscapeuser",
            name="instagram",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="soundscapeuser",
            name="x",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="soundscapeuser",
            name="youtube",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
