# Generated by Django 5.1.3 on 2025-03-26 03:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_friendrequest_friendship"),
        ("users", "0030_soundscapeuser_instagram_soundscapeuser_x_and_more"),
    ]

    operations = []
