# Generated by Django 5.1.7 on 2025-03-26 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_merge_20250325_2300"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcertAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concert_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concert_attendances",
                        to="users.soundscapeuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "concert_id")},
            },
        ),
    ]
