# Generated by Django 5.1.7 on 2025-03-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="event_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
