# users/urls.py
from django.urls import path
from .views import (
    SpotifyCurrentUserView,
    UserTopArtistsView,
    UserTopTracksView,
    UserSavedAlbumsView,
    SpotifyLoginView,
    SpotifyCallbackView,
    TopGenresView,
    TopSongsForReviewPage,
    FetchSingleTrack,
    PutReviewInDB,
    GetReviewBySong,
    RecentlyListened,
    SongsSearch,
    GetSoundScapeProfile,
    GetReviewByUser,
    GetFriendRecs,
    UpdateSocialMedia,
    signin,
    signup,
    logout,
    get_name,
    google_auth,
    get_all_users,
    search_users,
    verify_email,
    send_friend_request,
    accept_friend_request,
    reject_friend_request,
    cancel_friend_request,
    incoming_friend_requests,
    outgoing_friend_requests,
    friends,
    request_password_reset,
    reset_password,
    monthly_top5_genres,
    toggle_concert_attendance,
    get_user_attending_concerts,
    invite_friend_to_concert,
    get_notifications,
    mark_notification_read,
    delete_notification,
    get_chats,
    create_chat,
    get_chat_messages,
    mark_messages_read,
)

app_name = "users"

urlpatterns = [
    path("", SpotifyCurrentUserView.as_view(), name="spotify-user"),
    path("top-artists/", UserTopArtistsView.as_view(), name="spotify-user-top-artists"),
    path("top-tracks/", UserTopTracksView.as_view(), name="spotify-user-top-tracks"),
    path(
        "saved-albums/", UserSavedAlbumsView.as_view(), name="spotify-user-saved-albums"
    ),
    path("login/", SpotifyLoginView.as_view(), name="spotify-login"),
    path("callback/", SpotifyCallbackView.as_view(), name="spotify-callback"),
    path("top-genres/", TopGenresView.as_view(), name="top-genre"),
    path(
        "top-songs-from-database/",
        TopSongsForReviewPage.as_view(),
        name="top-songs-from-database",
    ),
    path("fetch-single-track/", FetchSingleTrack.as_view(), name="fetch-single-track"),
    path("add-single-review/", PutReviewInDB.as_view(), name="add-single-review"),
    path("get-review-by-song/", GetReviewBySong.as_view(), name="get-review-by-song"),    
    path("get-review-by-user/", GetReviewByUser.as_view(), name="get-review-by-user"),
    path("recently-listened/", RecentlyListened.as_view(), name="recently-listened"),
    path("search-songs/", SongsSearch.as_view(), name="recently-listened"),
    path("friend-recs/", GetFriendRecs.as_view(), name="friend-recs"),
    path("signin/", signin, name="signin"),
    path("google_signin/", google_auth, name="google_signin"),
    path("signup/", signup, name="signup"),
    path("logout/", logout, name="logout"),
    path("get_name/", get_name, name="get_name"),
    path("get-user-profile/", GetSoundScapeProfile.as_view(), name="get-user-profile"),
    path("all-users/", get_all_users, name="all-users"),
    path("search/", search_users, name="search-users"),
    path("update-social-media/", UpdateSocialMedia.as_view(), name="update-social-media"),
    path("verifyemail/", verify_email, name="verify-email"),
    path("friend-requests/send/", send_friend_request, name="send-friend-request"),
    path("friend-requests/accept/<int:request_id>/", accept_friend_request, name="accept-friend-request"),
    path("friend-requests/reject/<int:request_id>/", reject_friend_request, name="reject-friend-request"),
    path("friend-requests/cancel/<int:request_id>/", cancel_friend_request, name="cancel-friend-request"),
    path("friend-requests/incoming/", incoming_friend_requests, name="incoming-friend-requests"),
    path("friend-requests/outgoing/", outgoing_friend_requests, name="outgoing-friend-requests"),
    path("friends/", friends, name="friends"),
    path("forgot-password/", request_password_reset, name="forgot-password"),
    path("reset-password/", reset_password, name="reset-password"),
    path("month-top5-genres/", monthly_top5_genres, name="month-top5-genres"),
    path("toggle-attendance/", toggle_concert_attendance, name="toggle-concert-attendance"),
    path("attending-concerts/", get_user_attending_concerts, name="attending-concerts"),
    path('invite-friend-to-concert/', invite_friend_to_concert, name='invite_friend_to_concert'),
    path('notifications/', get_notifications, name='get_notifications'),
    path('mark-notification-read/', mark_notification_read, name='mark_notification_read'),
    path('notifications/<int:notification_id>/', delete_notification, name='delete_notification'),
    
    # Chat endpoints
    path('chats/', get_chats, name='get_chats'),
    path('chats/create/', create_chat, name='create_chat'),
    path('chats/<int:chat_id>/messages/', get_chat_messages, name='get_chat_messages'),
    path('chats/<int:chat_id>/mark-read/', mark_messages_read, name='mark_messages_read'),
]
