# Generated by Django 5.1.3 on 2025-01-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seededrecs",
            name="source",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="seededrecs",
            name="target",
            field=models.TextField(),
        ),
    ]
