# Generated by Django 5.1.3 on 2025-01-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0002_alter_seededrecs_source_alter_seededrecs_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="CosineSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField()),
                ("source", models.TextField()),
                ("target", models.TextField()),
                ("similarity", models.DecimalField(decimal_places=7, max_digits=8)),
            ],
            options={
                "db_table": "cosine_similarity",
            },
        ),
    ]
