# Generated by Django 5.1.2 on 2024-10-17 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "album_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("album_type", models.CharField(max_length=50)),
                ("release_date", models.DateField()),
                ("release_date_precision", models.CharField(max_length=10)),
                ("total_tracks", models.IntegerField()),
                ("spotify_url", models.URLField()),
                ("href", models.URLField()),
                ("uri", models.CharField(max_length=100)),
                ("popularity", models.IntegerField()),
                ("label", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "artist_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("popularity", models.IntegerField()),
                ("href", models.URLField()),
                ("spotify_uri", models.CharField(max_length=100)),
                ("external_url", models.URLField()),
                ("followers_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("genre_id", models.AutoField(primary_key=True, serialize=False)),
                ("genre_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AlbumArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.album"
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.artist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.artist"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.genre"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "track_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("disc_number", models.IntegerField()),
                ("track_number", models.IntegerField()),
                ("duration_ms", models.IntegerField()),
                ("explicit", models.BooleanField(default=False)),
                ("href", models.URLField()),
                ("spotify_url", models.URLField()),
                ("uri", models.CharField(max_length=100)),
                ("preview_url", models.URLField(blank=True, null=True)),
                ("popularity", models.IntegerField()),
                ("is_playable", models.BooleanField(default=True)),
                ("is_local", models.BooleanField(default=False)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.album"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.artist"
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.track"
                    ),
                ),
            ],
        ),
    ]
