# Generated by Django 5.1.2 on 2024-10-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="label",
        ),
        migrations.RemoveField(
            model_name="album",
            name="popularity",
        ),
    ]
