# Generated by Django 5.1.2 on 2024-10-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_remove_album_label_remove_album_popularity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="is_playable",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
