# Generated by Django 5.1.2 on 2024-10-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_alter_track_is_playable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_date",
            field=models.CharField(max_length=50),
        ),
    ]
