# Generated by Django 5.1.3 on 2024-12-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0004_alter_album_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="href",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="release_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="release_date_precision",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="spotify_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="total_tracks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="uri",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
