# Generated by Django 5.1.3 on 2024-12-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_alter_album_album_type_alter_album_href_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist",
            old_name="artist_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="spotify_uri",
            new_name="uri",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="external_url",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="followers_count",
        ),
        migrations.AddField(
            model_name="artist",
            name="external_urls",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="artist",
            name="followers",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="artist",
            name="genres",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="artist",
            name="images",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="artist",
            name="type",
            field=models.CharField(default="artist", max_length=50),
        ),
    ]
