# Generated by Django 5.1.3 on 2024-12-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_rename_artist_id_artist_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="followers",
            field=models.IntegerField(default=0),
        ),
    ]
