# Generated by Django 5.1.3 on 2024-12-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0007_alter_artist_followers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="genre_id",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="genre_name",
        ),
        migrations.AddField(
            model_name="genre",
            name="name",
            field=models.CharField(
                default="Unknown Genre", max_length=100, unique=True
            ),
        ),
        migrations.RemoveField(
            model_name="artist",
            name="genres",
        ),
        migrations.AddField(
            model_name="artist",
            name="genres",
            field=models.ManyToManyField(related_name="artists", to="music.genre"),
        ),
    ]
