# Generated by Django 5.1.3 on 2024-12-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0008_rename_genre_id_genre_id_remove_genre_genre_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="art",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
