# Generated by Django 5.1.3 on 2024-12-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0009_track_art"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="artist",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
