# Generated by Django 5.1.3 on 2024-12-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0010_track_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="art",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
