# Generated by Django 5.1.3 on 2025-01-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0011_album_art"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artistgenre",
            name="artist",
        ),
        migrations.RemoveField(
            model_name="artistgenre",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="trackartist",
            name="artist",
        ),
        migrations.RemoveField(
            model_name="trackartist",
            name="track",
        ),
        migrations.RemoveField(
            model_name="track",
            name="artist",
        ),
        migrations.AddField(
            model_name="album",
            name="artists",
            field=models.ManyToManyField(
                blank=True, related_name="albums", to="music.artist"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="artists",
            field=models.ManyToManyField(
                blank=True, related_name="tracks", to="music.artist"
            ),
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("playlist_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("collaborative", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("external_url", models.URLField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("public", models.BooleanField(default=True)),
                ("owner_id", models.CharField(blank=True, max_length=50, null=True)),
                ("uri", models.CharField(blank=True, max_length=100)),
                (
                    "tracks",
                    models.ManyToManyField(
                        blank=True, related_name="playlists", to="music.track"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AlbumArtist",
        ),
        migrations.DeleteModel(
            name="ArtistGenre",
        ),
        migrations.DeleteModel(
            name="TrackArtist",
        ),
    ]
