# Generated by Django 5.1.3 on 2025-01-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0012_remove_artistgenre_artist_remove_artistgenre_genre_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist",
            old_name="id",
            new_name="artist_id",
        ),
    ]
