# Generated by Django 5.1.3 on 2025-01-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0013_rename_id_artist_artist_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="tracks",
        ),
    ]
