# Generated by Django 5.1.3 on 2025-01-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0014_remove_playlist_tracks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="id",
        ),
        migrations.AlterField(
            model_name="playlist",
            name="playlist_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
