# Generated by Django 5.1.3 on 2025-01-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0015_remove_playlist_id_alter_playlist_playlist_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="tracks",
            field=models.ManyToManyField(
                blank=True, related_name="playlists", to="music.track"
            ),
        ),
    ]
